# Generated by Django 6.0.6 on 2026-06-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('SEMI_ANNUAL', 'Semestriel'), ('YEARLY', 'Annuel')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenant')),
            ],
        ),
    ]
